server:
  port: 8080

spring:
  application:
    name: rate-gateway
  main:
    banner-mode: "off"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
